package com.sgepit.pmis.tenders.hbm;

/**
 * TenCom generated by MyEclipse Persistence Tools
 */

public class TenCom implements java.io.Serializable {

	// Fields

	private String comid;

	private String comname;

	private String comdept;

	private String comspeci;

	private String comno;

	private String pid;

	// Constructors

	/** default constructor */
	public TenCom() {
	}

	/** minimal constructor */
	public TenCom(String comid) {
		this.comid = comid;
	}

	/** full constructor */
	public TenCom(String comid, String comname, String comdept,
			String comspeci, String comno, String pid) {
		this.comid = comid;
		this.comname = comname;
		this.comdept = comdept;
		this.comspeci = comspeci;
		this.comno = comno;
		this.pid = pid;
	}

	// Property accessors

	public String getComid() {
		return this.comid;
	}

	public void setComid(String comid) {
		this.comid = comid;
	}

	public String getComname() {
		return this.comname;
	}

	public void setComname(String comname) {
		this.comname = comname;
	}

	public String getComdept() {
		return this.comdept;
	}

	public void setComdept(String comdept) {
		this.comdept = comdept;
	}

	public String getComspeci() {
		return this.comspeci;
	}

	public void setComspeci(String comspeci) {
		this.comspeci = comspeci;
	}

	public String getComno() {
		return this.comno;
	}

	public void setComno(String comno) {
		this.comno = comno;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

}