package com.sgepit.pmis.tenders.hbm;

/**
 * TenReg generated by MyEclipse Persistence Tools
 */

public class TenReg implements java.io.Serializable {

	// Fields

	private String regid;

	private String pid;

	private String regno;

	private String regnoid;

	private String regroup;

	private String regduty;

	// Constructors

	/** default constructor */
	public TenReg() {
	}

	/** minimal constructor */
	public TenReg(String regid) {
		this.regid = regid;
	}

	/** full constructor */
	public TenReg(String regid, String pid, String regno, String regnoid,
			String regroup, String regduty) {
		this.regid = regid;
		this.pid = pid;
		this.regno = regno;
		this.regnoid = regnoid;
		this.regroup = regroup;
		this.regduty = regduty;
	}

	// Property accessors

	public String getRegid() {
		return this.regid;
	}

	public void setRegid(String regid) {
		this.regid = regid;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getRegno() {
		return this.regno;
	}

	public void setRegno(String regno) {
		this.regno = regno;
	}

	public String getRegnoid() {
		return this.regnoid;
	}

	public void setRegnoid(String regnoid) {
		this.regnoid = regnoid;
	}

	public String getRegroup() {
		return this.regroup;
	}

	public void setRegroup(String regroup) {
		this.regroup = regroup;
	}

	public String getRegduty() {
		return this.regduty;
	}

	public void setRegduty(String regduty) {
		this.regduty = regduty;
	}

}