package com.sgepit.pmis.tenders.hbm;

import java.util.Date;

/**
 * TenSub generated by MyEclipse Persistence Tools
 */

public class TenSub implements java.io.Serializable {

	// Fields

	private String subid;

	private String pid;

	private String subno;

	private String subsubname;

	private Date subinputdate;

	private String submode;

	private Double submoney;

	private String subcomment;

	private Date subplandate;

	private String tsubarea;

	private String subordertype;

	// Constructors

	/** default constructor */
	public TenSub() {
	}

	/** minimal constructor */
	public TenSub(String subid, String pid, String subno) {
		this.subid = subid;
		this.pid = pid;
		this.subno = subno;
	}

	/** full constructor */
	public TenSub(String subid, String pid, String subno, String subsubname,
			Date subinputdate, String submode, Double submoney,
			String subcomment, Date subplandate, String tsubarea,
			String subordertype) {
		this.subid = subid;
		this.pid = pid;
		this.subno = subno;
		this.subsubname = subsubname;
		this.subinputdate = subinputdate;
		this.submode = submode;
		this.submoney = submoney;
		this.subcomment = subcomment;
		this.subplandate = subplandate;
		this.tsubarea = tsubarea;
		this.subordertype = subordertype;
	}

	// Property accessors

	public String getSubid() {
		return this.subid;
	}

	public void setSubid(String subid) {
		this.subid = subid;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getSubno() {
		return this.subno;
	}

	public void setSubno(String subno) {
		this.subno = subno;
	}

	public String getSubsubname() {
		return this.subsubname;
	}

	public void setSubsubname(String subsubname) {
		this.subsubname = subsubname;
	}

	public Date getSubinputdate() {
		return this.subinputdate;
	}

	public void setSubinputdate(Date subinputdate) {
		this.subinputdate = subinputdate;
	}

	public String getSubmode() {
		return this.submode;
	}

	public void setSubmode(String submode) {
		this.submode = submode;
	}

	public Double getSubmoney() {
		return this.submoney;
	}

	public void setSubmoney(Double submoney) {
		this.submoney = submoney;
	}

	public String getSubcomment() {
		return this.subcomment;
	}

	public void setSubcomment(String subcomment) {
		this.subcomment = subcomment;
	}

	public Date getSubplandate() {
		return this.subplandate;
	}

	public void setSubplandate(Date subplandate) {
		this.subplandate = subplandate;
	}

	public String getTsubarea() {
		return this.tsubarea;
	}

	public void setTsubarea(String tsubarea) {
		this.tsubarea = tsubarea;
	}

	public String getSubordertype() {
		return this.subordertype;
	}

	public void setSubordertype(String subordertype) {
		this.subordertype = subordertype;
	}

}