package com.sgepit.pmis.tenders.hbm;

import java.util.Date;

/**
 * TenUni generated by MyEclipse Persistence Tools
 */

public class TenUni implements java.io.Serializable {

	// Fields

	private String cleid;

	private String clepid;

	private String pid;

	private String cleno;

	private String clename;

	private Date cledate;

	private String clemaintype;

	private Double clemoney;

	private Double cletomoney;

	// Constructors

	/** default constructor */
	public TenUni() {
	}

	/** minimal constructor */
	public TenUni(String cleid) {
		this.cleid = cleid;
	}

	/** full constructor */
	public TenUni(String cleid, String clepid, String pid, String cleno,
			String clename, Date cledate, String clemaintype, Double clemoney,
			Double cletomoney) {
		this.cleid = cleid;
		this.clepid = clepid;
		this.pid = pid;
		this.cleno = cleno;
		this.clename = clename;
		this.cledate = cledate;
		this.clemaintype = clemaintype;
		this.clemoney = clemoney;
		this.cletomoney = cletomoney;
	}

	// Property accessors

	public String getCleid() {
		return this.cleid;
	}

	public void setCleid(String cleid) {
		this.cleid = cleid;
	}

	public String getClepid() {
		return this.clepid;
	}

	public void setClepid(String clepid) {
		this.clepid = clepid;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getCleno() {
		return this.cleno;
	}

	public void setCleno(String cleno) {
		this.cleno = cleno;
	}

	public String getClename() {
		return this.clename;
	}

	public void setClename(String clename) {
		this.clename = clename;
	}

	public Date getCledate() {
		return this.cledate;
	}

	public void setCledate(Date cledate) {
		this.cledate = cledate;
	}

	public String getClemaintype() {
		return this.clemaintype;
	}

	public void setClemaintype(String clemaintype) {
		this.clemaintype = clemaintype;
	}

	public Double getClemoney() {
		return this.clemoney;
	}

	public void setClemoney(Double clemoney) {
		this.clemoney = clemoney;
	}

	public Double getCletomoney() {
		return this.cletomoney;
	}

	public void setCletomoney(Double cletomoney) {
		this.cletomoney = cletomoney;
	}
}