package com.sgepit.pmis.tenders.hbm;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pbasic generated by MyEclipse Persistence Tools
 */

public class Pbasic implements java.io.Serializable {

	// Fields


	// Fields

	private String proid;

	private String proname;

	private String protype;

	private String prokind;

	private String procomname;

	private String promome;

	private String proadr;

	private String propost;

	private String procomadr;

	private String proyorn;

	private Date prostadt;

	private Date proenddate;

	private Date proinststadt;

	private Date proplanstadt;

	private Long probuild;

	private Double proarmcont;

	private Long promacont;

	private Double prostatcovt;

	private Double protredcont;

	private String proypoint;

	private String proystatcony;

	private String pid;

	private Set zbBasics = new HashSet(0);

	// Constructors

	/** default constructor */
	public Pbasic() {
	}

	/** minimal constructor */
	public Pbasic(String proid) {
		this.proid = proid;
	}

	/** full constructor */
	public Pbasic(String proid, String proname, String protype, String prokind,
			String procomname, String promome, String proadr, String propost,
			String procomadr, String proyorn, Date prostadt, Date proenddate,
			Date proinststadt, Date proplanstadt, Long probuild,
			Double proarmcont, Long promacont, Double prostatcovt,
			Double protredcont, String proypoint, String proystatcony,
			String pid, Set zbBasics) {
		this.proid = proid;
		this.proname = proname;
		this.protype = protype;
		this.prokind = prokind;
		this.procomname = procomname;
		this.promome = promome;
		this.proadr = proadr;
		this.propost = propost;
		this.procomadr = procomadr;
		this.proyorn = proyorn;
		this.prostadt = prostadt;
		this.proenddate = proenddate;
		this.proinststadt = proinststadt;
		this.proplanstadt = proplanstadt;
		this.probuild = probuild;
		this.proarmcont = proarmcont;
		this.promacont = promacont;
		this.prostatcovt = prostatcovt;
		this.protredcont = protredcont;
		this.proypoint = proypoint;
		this.proystatcony = proystatcony;
		this.pid = pid;
		this.zbBasics = zbBasics;
	}

	// Property accessors

	public String getProid() {
		return this.proid;
	}

	public void setProid(String proid) {
		this.proid = proid;
	}

	public String getProname() {
		return this.proname;
	}

	public void setProname(String proname) {
		this.proname = proname;
	}

	public String getProtype() {
		return this.protype;
	}

	public void setProtype(String protype) {
		this.protype = protype;
	}

	public String getProkind() {
		return this.prokind;
	}

	public void setProkind(String prokind) {
		this.prokind = prokind;
	}

	public String getProcomname() {
		return this.procomname;
	}

	public void setProcomname(String procomname) {
		this.procomname = procomname;
	}

	public String getPromome() {
		return this.promome;
	}

	public void setPromome(String promome) {
		this.promome = promome;
	}

	public String getProadr() {
		return this.proadr;
	}

	public void setProadr(String proadr) {
		this.proadr = proadr;
	}

	public String getPropost() {
		return this.propost;
	}

	public void setPropost(String propost) {
		this.propost = propost;
	}

	public String getProcomadr() {
		return this.procomadr;
	}

	public void setProcomadr(String procomadr) {
		this.procomadr = procomadr;
	}

	public String getProyorn() {
		return this.proyorn;
	}

	public void setProyorn(String proyorn) {
		this.proyorn = proyorn;
	}

	public Date getProstadt() {
		return this.prostadt;
	}

	public void setProstadt(Date prostadt) {
		this.prostadt = prostadt;
	}

	public Date getProenddate() {
		return this.proenddate;
	}

	public void setProenddate(Date proenddate) {
		this.proenddate = proenddate;
	}

	public Date getProinststadt() {
		return this.proinststadt;
	}

	public void setProinststadt(Date proinststadt) {
		this.proinststadt = proinststadt;
	}

	public Date getProplanstadt() {
		return this.proplanstadt;
	}

	public void setProplanstadt(Date proplanstadt) {
		this.proplanstadt = proplanstadt;
	}

	public Long getProbuild() {
		return this.probuild;
	}

	public void setProbuild(Long probuild) {
		this.probuild = probuild;
	}

	public Double getProarmcont() {
		return this.proarmcont;
	}

	public void setProarmcont(Double proarmcont) {
		this.proarmcont = proarmcont;
	}

	public Long getPromacont() {
		return this.promacont;
	}

	public void setPromacont(Long promacont) {
		this.promacont = promacont;
	}

	public Double getProstatcovt() {
		return this.prostatcovt;
	}

	public void setProstatcovt(Double prostatcovt) {
		this.prostatcovt = prostatcovt;
	}

	public Double getProtredcont() {
		return this.protredcont;
	}

	public void setProtredcont(Double protredcont) {
		this.protredcont = protredcont;
	}

	public String getProypoint() {
		return this.proypoint;
	}

	public void setProypoint(String proypoint) {
		this.proypoint = proypoint;
	}

	public String getProystatcony() {
		return this.proystatcony;
	}

	public void setProystatcony(String proystatcony) {
		this.proystatcony = proystatcony;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public Set getZbBasics() {
		return this.zbBasics;
	}

	public void setZbBasics(Set zbBasics) {
		this.zbBasics = zbBasics;
	}
}