package com.sgepit.pmis.tenders.hbm;

/**
 * TenAbi generated by MyEclipse Persistence Tools
 */

public class TenAbi implements java.io.Serializable {

	// Fields

	private String peoid;

	private String peoname;

	private String peodept;

	private String peoduty;

	private String peospeci;

	private String reomark;

	private String peotecspec;

	private String peotecfield;

	private String peosex;

	private String peotel;

	private String peoemail;

	private String pid;

	private String peono;

	private String peotecpost;

	// Constructors

	/** default constructor */
	public TenAbi() {
	}

	/** minimal constructor */
	public TenAbi(String peoid) {
		this.peoid = peoid;
	}

	/** full constructor */
	public TenAbi(String peoid, String peoname, String peodept, String peoduty,
			String peospeci, String reomark, String peotecspec,
			String peotecfield, String peosex, String peotel, String peoemail,
			String pid, String peono, String peotecpost) {
		this.peoid = peoid;
		this.peoname = peoname;
		this.peodept = peodept;
		this.peoduty = peoduty;
		this.peospeci = peospeci;
		this.reomark = reomark;
		this.peotecspec = peotecspec;
		this.peotecfield = peotecfield;
		this.peosex = peosex;
		this.peotel = peotel;
		this.peoemail = peoemail;
		this.pid = pid;
		this.peono = peono;
		this.peotecpost = peotecpost;
	}

	// Property accessors

	public String getPeoid() {
		return this.peoid;
	}

	public void setPeoid(String peoid) {
		this.peoid = peoid;
	}

	public String getPeoname() {
		return this.peoname;
	}

	public void setPeoname(String peoname) {
		this.peoname = peoname;
	}

	public String getPeodept() {
		return this.peodept;
	}

	public void setPeodept(String peodept) {
		this.peodept = peodept;
	}

	public String getPeoduty() {
		return this.peoduty;
	}

	public void setPeoduty(String peoduty) {
		this.peoduty = peoduty;
	}

	public String getPeospeci() {
		return this.peospeci;
	}

	public void setPeospeci(String peospeci) {
		this.peospeci = peospeci;
	}

	public String getReomark() {
		return this.reomark;
	}

	public void setReomark(String reomark) {
		this.reomark = reomark;
	}

	public String getPeotecspec() {
		return this.peotecspec;
	}

	public void setPeotecspec(String peotecspec) {
		this.peotecspec = peotecspec;
	}

	public String getPeotecfield() {
		return this.peotecfield;
	}

	public void setPeotecfield(String peotecfield) {
		this.peotecfield = peotecfield;
	}

	public String getPeosex() {
		return this.peosex;
	}

	public void setPeosex(String peosex) {
		this.peosex = peosex;
	}

	public String getPeotel() {
		return this.peotel;
	}

	public void setPeotel(String peotel) {
		this.peotel = peotel;
	}

	public String getPeoemail() {
		return this.peoemail;
	}

	public void setPeoemail(String peoemail) {
		this.peoemail = peoemail;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getPeono() {
		return this.peono;
	}

	public void setPeono(String peono) {
		this.peono = peono;
	}

	public String getPeotecpost() {
		return this.peotecpost;
	}

	public void setPeotecpost(String peotecpost) {
		this.peotecpost = peotecpost;
	}
}