package com.sgepit.pmis.tenders.hbm;

import java.util.Date;

/**
 * TenPro generated by MyEclipse Persistence Tools
 */

public class TenPro implements java.io.Serializable {

	// Fields

	private String tenid;

	private String tenno;

	private String tenname;

	private String tendept;

	private String tenprinc;

	private Date teninputdate;

	private Double tenmoney;

	private String tenmode;

	private String tenbound;

	private String tensendpc;

	private String tenmind;

	private String tencomment;

	private Date tenopendate;

	private String remark;

	private Double tenminiprice;

	private String tentype;

	private Double tenmainprice;

	private Double tencompar;

	private String tenfilenm;

	private String tenfileid;

	private String pid;

	// Constructors

	/** default constructor */
	public TenPro() {
	}

	/** minimal constructor */
	public TenPro(String tenid) {
		this.tenid = tenid;
	}

	/** full constructor */
	public TenPro(String tenid, String tenno, String tenname, String tendept,
			String tenprinc, Date teninputdate, Double tenmoney,
			String tenmode, String tenbound, String tensendpc, String tenmind,
			String tencomment, Date tenopendate, String remark,
			Double tenminiprice, String tentype, Double tenmainprice,
			Double tencompar, String tenfilenm, String tenfileid, String pid) {
		this.tenid = tenid;
		this.tenno = tenno;
		this.tenname = tenname;
		this.tendept = tendept;
		this.tenprinc = tenprinc;
		this.teninputdate = teninputdate;
		this.tenmoney = tenmoney;
		this.tenmode = tenmode;
		this.tenbound = tenbound;
		this.tensendpc = tensendpc;
		this.tenmind = tenmind;
		this.tencomment = tencomment;
		this.tenopendate = tenopendate;
		this.remark = remark;
		this.tenminiprice = tenminiprice;
		this.tentype = tentype;
		this.tenmainprice = tenmainprice;
		this.tencompar = tencompar;
		this.tenfilenm = tenfilenm;
		this.tenfileid = tenfileid;
		this.pid = pid;
	}

	// Property accessors

	public String getTenid() {
		return this.tenid;
	}

	public void setTenid(String tenid) {
		this.tenid = tenid;
	}

	public String getTenno() {
		return this.tenno;
	}

	public void setTenno(String tenno) {
		this.tenno = tenno;
	}

	public String getTenname() {
		return this.tenname;
	}

	public void setTenname(String tenname) {
		this.tenname = tenname;
	}

	public String getTendept() {
		return this.tendept;
	}

	public void setTendept(String tendept) {
		this.tendept = tendept;
	}

	public String getTenprinc() {
		return this.tenprinc;
	}

	public void setTenprinc(String tenprinc) {
		this.tenprinc = tenprinc;
	}

	public Date getTeninputdate() {
		return this.teninputdate;
	}

	public void setTeninputdate(Date teninputdate) {
		this.teninputdate = teninputdate;
	}

	public Double getTenmoney() {
		return this.tenmoney;
	}

	public void setTenmoney(Double tenmoney) {
		this.tenmoney = tenmoney;
	}

	public String getTenmode() {
		return this.tenmode;
	}

	public void setTenmode(String tenmode) {
		this.tenmode = tenmode;
	}

	public String getTenbound() {
		return this.tenbound;
	}

	public void setTenbound(String tenbound) {
		this.tenbound = tenbound;
	}

	public String getTensendpc() {
		return this.tensendpc;
	}

	public void setTensendpc(String tensendpc) {
		this.tensendpc = tensendpc;
	}

	public String getTenmind() {
		return this.tenmind;
	}

	public void setTenmind(String tenmind) {
		this.tenmind = tenmind;
	}

	public String getTencomment() {
		return this.tencomment;
	}

	public void setTencomment(String tencomment) {
		this.tencomment = tencomment;
	}

	public Date getTenopendate() {
		return this.tenopendate;
	}

	public void setTenopendate(Date tenopendate) {
		this.tenopendate = tenopendate;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Double getTenminiprice() {
		return this.tenminiprice;
	}

	public void setTenminiprice(Double tenminiprice) {
		this.tenminiprice = tenminiprice;
	}

	public String getTentype() {
		return this.tentype;
	}

	public void setTentype(String tentype) {
		this.tentype = tentype;
	}

	public Double getTenmainprice() {
		return this.tenmainprice;
	}

	public void setTenmainprice(Double tenmainprice) {
		this.tenmainprice = tenmainprice;
	}

	public Double getTencompar() {
		return this.tencompar;
	}

	public void setTencompar(Double tencompar) {
		this.tencompar = tencompar;
	}

	public String getTenfilenm() {
		return this.tenfilenm;
	}

	public void setTenfilenm(String tenfilenm) {
		this.tenfilenm = tenfilenm;
	}

	public String getTenfileid() {
		return this.tenfileid;
	}

	public void setTenfileid(String tenfileid) {
		this.tenfileid = tenfileid;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

}