package com.sgepit.pmis.tenders.hbm;

import java.util.Date;

/**
 * ZbJh generated by MyEclipse Persistence Tools
 */

public class ZbJh implements java.io.Serializable {

	// Fields

	private String tenid;

	private String tenpid;

	private String tenno;

	private String tensubname;

	private Date teninputdate;

	private String tenmode;

	private Double tenmoney;

	private String tencomment;

	private Date tenplandate;

	private String tenarea;

	private String tenordertype;

	// Constructors

	/** default constructor */
	public ZbJh() {
	}

	/** minimal constructor */
	public ZbJh(String tenid, String tenpid, String tenno) {
		this.tenid = tenid;
		this.tenpid = tenpid;
		this.tenno = tenno;
	}

	/** full constructor */
	public ZbJh(String tenid, String tenpid, String tenno, String tensubname,
			Date teninputdate, String tenmode, Double tenmoney,
			String tencomment, Date tenplandate, String tenarea,
			String tenordertype) {
		this.tenid = tenid;
		this.tenpid = tenpid;
		this.tenno = tenno;
		this.tensubname = tensubname;
		this.teninputdate = teninputdate;
		this.tenmode = tenmode;
		this.tenmoney = tenmoney;
		this.tencomment = tencomment;
		this.tenplandate = tenplandate;
		this.tenarea = tenarea;
		this.tenordertype = tenordertype;
	}

	// Property accessors

	public String getTenid() {
		return this.tenid;
	}

	public void setTenid(String tenid) {
		this.tenid = tenid;
	}

	public String getTenpid() {
		return this.tenpid;
	}

	public void setTenpid(String tenpid) {
		this.tenpid = tenpid;
	}

	public String getTenno() {
		return this.tenno;
	}

	public void setTenno(String tenno) {
		this.tenno = tenno;
	}

	public String getTensubname() {
		return this.tensubname;
	}

	public void setTensubname(String tensubname) {
		this.tensubname = tensubname;
	}

	public Date getTeninputdate() {
		return this.teninputdate;
	}

	public void setTeninputdate(Date teninputdate) {
		this.teninputdate = teninputdate;
	}

	public String getTenmode() {
		return this.tenmode;
	}

	public void setTenmode(String tenmode) {
		this.tenmode = tenmode;
	}

	public Double getTenmoney() {
		return this.tenmoney;
	}

	public void setTenmoney(Double tenmoney) {
		this.tenmoney = tenmoney;
	}

	public String getTencomment() {
		return this.tencomment;
	}

	public void setTencomment(String tencomment) {
		this.tencomment = tencomment;
	}

	public Date getTenplandate() {
		return this.tenplandate;
	}

	public void setTenplandate(Date tenplandate) {
		this.tenplandate = tenplandate;
	}

	public String getTenarea() {
		return this.tenarea;
	}

	public void setTenarea(String tenarea) {
		this.tenarea = tenarea;
	}

	public String getTenordertype() {
		return this.tenordertype;
	}

	public void setTenordertype(String tenordertype) {
		this.tenordertype = tenordertype;
	}

}