package com.sgepit.pmis.tenders.hbm;

/**
 * ZbPw generated by MyEclipse Persistence Tools
 */

public class ZbPw implements java.io.Serializable {

	// Fields

	private String tenid;

	private String tenpid;

	private String prono;

	private String zbgroup;

	private String zbpart;

	// Constructors

	/** default constructor */
	public ZbPw() {
	}

	/** minimal constructor */
	public ZbPw(String tenid, String tenpid, String prono) {
		this.tenid = tenid;
		this.tenpid = tenpid;
		this.prono = prono;
	}

	/** full constructor */
	public ZbPw(String tenid, String tenpid, String prono, String zbgroup,
			String zbpart) {
		this.tenid = tenid;
		this.tenpid = tenpid;
		this.prono = prono;
		this.zbgroup = zbgroup;
		this.zbpart = zbpart;
	}

	// Property accessors

	public String getTenid() {
		return this.tenid;
	}

	public void setTenid(String tenid) {
		this.tenid = tenid;
	}

	public String getTenpid() {
		return this.tenpid;
	}

	public void setTenpid(String tenpid) {
		this.tenpid = tenpid;
	}

	public String getProno() {
		return this.prono;
	}

	public void setProno(String prono) {
		this.prono = prono;
	}

	public String getZbgroup() {
		return this.zbgroup;
	}

	public void setZbgroup(String zbgroup) {
		this.zbgroup = zbgroup;
	}

	public String getZbpart() {
		return this.zbpart;
	}

	public void setZbpart(String zbpart) {
		this.zbpart = zbpart;
	}

}