package com.sgepit.pmis.tenders.hbm;

/**
 * ZbRck generated by MyEclipse Persistence Tools
 */

public class ZbRck implements java.io.Serializable {

	// Fields

	private String tenid;

	private Pbasic pbasic;

	private String tenpid;

	private String peoname;

	private String peosex;

	private String peotel;

	private String peoemail;

	private String peodept;

	private String peodiplo;

	private String peoduty;

	private String peotecpost;

	private String peotecspec;

	private String peotecfield;

	// Constructors

	/** default constructor */
	public ZbRck() {
	}

	/** minimal constructor */
	public ZbRck(String tenid, Pbasic pbasic, String tenpid) {
		this.tenid = tenid;
		this.pbasic = pbasic;
		this.tenpid = tenpid;
	}

	/** full constructor */
	public ZbRck(String tenid, Pbasic pbasic, String tenpid, String peoname,
			String peosex, String peotel, String peoemail, String peodept,
			String peodiplo, String peoduty, String peotecpost,
			String peotecspec, String peotecfield) {
		this.tenid = tenid;
		this.pbasic = pbasic;
		this.tenpid = tenpid;
		this.peoname = peoname;
		this.peosex = peosex;
		this.peotel = peotel;
		this.peoemail = peoemail;
		this.peodept = peodept;
		this.peodiplo = peodiplo;
		this.peoduty = peoduty;
		this.peotecpost = peotecpost;
		this.peotecspec = peotecspec;
		this.peotecfield = peotecfield;
	}

	// Property accessors

	public String getTenid() {
		return this.tenid;
	}

	public void setTenid(String tenid) {
		this.tenid = tenid;
	}

	public Pbasic getPbasic() {
		return this.pbasic;
	}

	public void setPbasic(Pbasic pbasic) {
		this.pbasic = pbasic;
	}

	public String getTenpid() {
		return this.tenpid;
	}

	public void setTenpid(String tenpid) {
		this.tenpid = tenpid;
	}

	public String getPeoname() {
		return this.peoname;
	}

	public void setPeoname(String peoname) {
		this.peoname = peoname;
	}

	public String getPeosex() {
		return this.peosex;
	}

	public void setPeosex(String peosex) {
		this.peosex = peosex;
	}

	public String getPeotel() {
		return this.peotel;
	}

	public void setPeotel(String peotel) {
		this.peotel = peotel;
	}

	public String getPeoemail() {
		return this.peoemail;
	}

	public void setPeoemail(String peoemail) {
		this.peoemail = peoemail;
	}

	public String getPeodept() {
		return this.peodept;
	}

	public void setPeodept(String peodept) {
		this.peodept = peodept;
	}

	public String getPeodiplo() {
		return this.peodiplo;
	}

	public void setPeodiplo(String peodiplo) {
		this.peodiplo = peodiplo;
	}

	public String getPeoduty() {
		return this.peoduty;
	}

	public void setPeoduty(String peoduty) {
		this.peoduty = peoduty;
	}

	public String getPeotecpost() {
		return this.peotecpost;
	}

	public void setPeotecpost(String peotecpost) {
		this.peotecpost = peotecpost;
	}

	public String getPeotecspec() {
		return this.peotecspec;
	}

	public void setPeotecspec(String peotecspec) {
		this.peotecspec = peotecspec;
	}

	public String getPeotecfield() {
		return this.peotecfield;
	}

	public void setPeotecfield(String peotecfield) {
		this.peotecfield = peotecfield;
	}

}