package com.sgepit.pmis.tenders.hbm;

/**
 * ZbWyh generated by MyEclipse Persistence Tools
 */

public class ZbWyh implements java.io.Serializable {

	// Fields

	private String comid;

	private String comnum;

	private String compart;

	// Constructors

	/** default constructor */
	public ZbWyh() {
	}

	/** minimal constructor */
	public ZbWyh(String comid, String comnum) {
		this.comid = comid;
		this.comnum = comnum;
	}

	/** full constructor */
	public ZbWyh(String comid, String comnum, String compart) {
		this.comid = comid;
		this.comnum = comnum;
		this.compart = compart;
	}

	// Property accessors

	public String getComid() {
		return this.comid;
	}

	public void setComid(String comid) {
		this.comid = comid;
	}

	public String getComnum() {
		return this.comnum;
	}

	public void setComnum(String comnum) {
		this.comnum = comnum;
	}

	public String getCompart() {
		return this.compart;
	}

	public void setCompart(String compart) {
		this.compart = compart;
	}

}