package com.sgepit.frame.sysman.hbm;

import java.util.Date;


/**
 * SgccAttachList generated by MyEclipse - Hibernate Tools
 */

public class SgccAttachList  implements java.io.Serializable {


    // Fields    

     private SgccAttachListId id;
     private String fileType;
     private String fileName;
     private Date uploadDate;
     private String userid;
     private String memo;
     private String deptId;
     private String transId;
     private String transFlag;
     private String unitId;
     private String templateId;
     private String isCompress;
     private String fileSource;
     private Long fileSize;
     private String blobTable;
     private String isTrans;

    // Constructors

    public String getTransactionType() {
		return id.getTransactionType();
	}
	public String getTransactionId() {
		return id.getTransactionId();
	}
	public String getFileLsh() {
		return id.getFileLsh();
	}
	/**
	 * @return the fileSource
	 */
	public String getFileSource() {
		return fileSource;
	}

	/**
	 * @param fileSource the fileSource to set
	 */
	public void setFileSource(String fileSource) {
		this.fileSource = fileSource;
	}

	public String getDeptId() {
		return deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	/** default constructor */
    public SgccAttachList() {
    }

	/** minimal constructor */
    public SgccAttachList(SgccAttachListId id) {
        this.id = id;
    }
    
    /** full constructor */
    public SgccAttachList(SgccAttachListId id, String fileType, String fileName, Date uploadDate, String userid, String memo) {
        this.id = id;
        this.fileType = fileType;
        this.fileName = fileName;
        this.uploadDate = uploadDate;
        this.userid = userid;
        this.memo = memo;
    }

   
    // Property accessors

    public SgccAttachListId getId() {
        return this.id;
    }
    
    public void setId(SgccAttachListId id) {
        this.id = id;
    }

    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Date getUploadDate() {
        return this.uploadDate;
    }
    
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }

	public String getTransId() {
		return transId;
	}

	public void setTransId(String transId) {
		this.transId = transId;
	}

	public String getTransFlag() {
		return transFlag;
	}

	public void setTransFlag(String transFlag) {
		this.transFlag = transFlag;
	}

	public String getUnitId() {
		return unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	public String getTemplateId() {
		return templateId;
	}

	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	/**
	 * @return the isCompress
	 */
	public String getIsCompress() {
		return isCompress;
	}

	/**
	 * @param isCompress the isCompress to set
	 */
	public void setIsCompress(String isCompress) {
		this.isCompress = isCompress;
	}

	public String getStatus() {
		//已上传
		return "2";
	}
	public Long getFileSize() {
		return fileSize;
	}
	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}
	public String getBlobTable() {
		return blobTable;
	}
	public void setBlobTable(String blobTable) {
		this.blobTable = blobTable;
	}
	public String getIsTrans() {
		return isTrans;
	}
	public void setIsTrans(String isTrans) {
		this.isTrans = isTrans;
	}

	







}