package com.sgepit.frame.sysman.hbm;

/**
 * RockPowerUserId generated by MyEclipse - Hibernate Tools
 */

public class RockPowerUserId  implements java.io.Serializable {


    // Fields    

     private String powerpk;
     private String userid;


    // Constructors

    /** default constructor */
    public RockPowerUserId() {
    }

    
    /** full constructor */
    public RockPowerUserId(String powerpk, String userid) {
        this.powerpk = powerpk;
        this.userid = userid;
    }


	/**
	 * @return the powerpk
	 */
	public String getPowerpk() {
		return powerpk;
	}


	/**
	 * @param powerpk the powerpk to set
	 */
	public void setPowerpk(String powerpk) {
		this.powerpk = powerpk;
	}


	/**
	 * @return the userid
	 */
	public String getUserid() {
		return userid;
	}


	/**
	 * @param userid the userid to set
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

   

	public boolean equals(Object other) {
	         if ( (this == other ) ) return true;
			 if ( (other == null ) ) return false;
			 if ( !(other instanceof RockPowerUserId) ) return false;
			 RockPowerUserId castOther = ( RockPowerUserId ) other; 
	         
			 return ( (this.getPowerpk()==castOther.getPowerpk()) || ( this.getPowerpk()!=null && castOther.getPowerpk()!=null && this.getPowerpk().equals(castOther.getPowerpk()) ) )
	 && ( (this.getUserid()==castOther.getUserid()) || ( this.getUserid()!=null && castOther.getUserid()!=null && this.getUserid().equals(castOther.getUserid()) ) );
	   }
	   
	   public int hashCode() {
	         int result = 17;
	         
	         result = 37 * result + ( getPowerpk() == null ? 0 : this.getPowerpk().hashCode() );
	         result = 37 * result + ( getUserid() == null ? 0 : this.getUserid().hashCode() );
	         return result;
	   }   





}