package com.sgepit.frame.sysman.hbm;



/**
 * SgccAttachListId generated by MyEclipse - Hibernate Tools
 */

public class SgccAttachListId  implements java.io.Serializable {


    // Fields    

     private String transactionType;
     private String transactionId;
     private String fileLsh;


    // Constructors

    /** default constructor */
    public SgccAttachListId() {
    }

    
    /** full constructor */
    public SgccAttachListId(String transactionType, String transactionId, String fileLsh) {
        this.transactionType = transactionType;
        this.transactionId = transactionId;
        this.fileLsh = fileLsh;
    }

   
    // Property accessors

    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    public String getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getFileLsh() {
        return this.fileLsh;
    }
    
    public void setFileLsh(String fileLsh) {
        this.fileLsh = fileLsh;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgccAttachListId) ) return false;
		 SgccAttachListId castOther = ( SgccAttachListId ) other; 
         
		 return ( (this.getTransactionType()==castOther.getTransactionType()) || ( this.getTransactionType()!=null && castOther.getTransactionType()!=null && this.getTransactionType().equals(castOther.getTransactionType()) ) )
 && ( (this.getTransactionId()==castOther.getTransactionId()) || ( this.getTransactionId()!=null && castOther.getTransactionId()!=null && this.getTransactionId().equals(castOther.getTransactionId()) ) )
 && ( (this.getFileLsh()==castOther.getFileLsh()) || ( this.getFileLsh()!=null && castOther.getFileLsh()!=null && this.getFileLsh().equals(castOther.getFileLsh()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTransactionType() == null ? 0 : this.getTransactionType().hashCode() );
         result = 37 * result + ( getTransactionId() == null ? 0 : this.getTransactionId().hashCode() );
         result = 37 * result + ( getFileLsh() == null ? 0 : this.getFileLsh().hashCode() );
         return result;
   }   





}