<%@ page language="java" pageEncoding="UTF-8" %>
<HTML>
<HEAD>
   <TITLE>Applet HTML Page</TITLE>
   <%@ include file="../common/golobalJs.jsp" %>
	<script type='text/javascript' src='dwr/interface/flwLogMgm.js'></script>
	<script type='text/javascript' src='dwr/engine.js'></script>

	<script type='text/javascript'>
		function createXML(){
			flwLogMgm.createXML(document.getElementById("xml").value);
		}
		function saveFigures(xmlOutput, allFigureInfo){
			document.getElementById("xml").value = xmlOutput;
			document.getElementById("figures").value = allFigureInfo;
		}
	</script>
</HEAD>
<BODY>

<H3><HR WIDTH="100%">Applet HTML Page<HR WIDTH="100%"></H3>
<center>
<P>
<applet code="org.jhotdraw.samples.draw.DemoApplet"
	  name="demoApplet" width="700" height="400" archive="DemoDraw.jar" id="demoApplet">
    <param name="datafile" value="../../temp/<%="35fee4ac-9a0d-42f2-84df-5d55f444fdfa.xml" %>" />
</applet>
</P>

<HR WIDTH="100%"><FONT SIZE=-1><I>See the create xml codes</I></FONT>
<br>
<textarea id="xml" rows="25" cols="100"></textarea>
<br>
<textarea id="figures" rows="25" cols="100"></textarea>
<br>
<button onclick="createXML()">生成xml</button>
</center>
<HR WIDTH="100%"><FONT SIZE=-1><I>Generated by NetBeans IDE</I></FONT>
</BODY>
</HTML>
